### ISSUE TITLE
Gitlab diffs exception works only after reapplying customization

### ISSUE THREAD

**Issue by MartyBeGood** [alexanderby/darkreader#317] opened 2018-03-26 12:02 UTC
Normal code views in gitlab look fine.
Diff views (e.g. in a merge request) with a dark theme (i.e. .code.dark, .code.solarized-dark and .code.monokai) are getting inverted even though they are listed in the customization json. When you open the dev tools and click 'apply' (without changing the actual content of the customization json), the diff views are not getting inverted anymore (expected behaviour) until you restart the browser.
Tested in Firefox 59.0.1 and Vivaldi 1.14.1077.55

**Comment by MartyBeGood** [comment] 2018-03-27 08:46
Same thing for the emojis (add "gl-emoji" to "invert")

Reproduction:
- Add mentioned selectors to inversion fix editor
- Click apply
- Everything should look fine
- Restart browser
- Diff views and Emojis are wrongly inverted
- Open inversion fix editor
- Click apply
- Diff views and Emojis are un-inverted

**Comment by alexanderby** [comment] 2018-03-27 08:55
The problem is that config is reloaded every 15 minutes and overwrites the changes https://github.com/alexanderby/darkreader/issues/143

This will be fixed in one of the next releases.

**Closed by alexanderby** 2018-03-27 08:55 UTC
Labels: duplicate
