### ISSUE TITLE
Suggestion: Detect if website is already dark

### ISSUE THREAD

**Issue by Lesik** [alexanderby/darkreader#225] opened 2018-02-14 16:42 UTC
What if we would detect if a website is already dark by checking whether the inverted colors are brighter than the original colors?

This would be useful in the following scenario, where one can't just blacklist the website in question, because the dark theme is dynamically applied on a per-user level:

![bildschirmfoto von 2018-02-14 17-21-09](https://user-images.githubusercontent.com/2021487/36216095-1aeddd7a-11ae-11e8-8ce7-ca7384441e05.png)

**Comment by alexanderby** [comment] 2018-02-17 08:39
Duplicate of https://github.com/alexanderby/darkreader/issues/81

**Closed by alexanderby** 2018-02-17 08:39 UTC
Labels: duplicate
