### ISSUE TITLE
Android FireFox - No go

### ISSUE THREAD

**Issue by halxinate** [alexanderby/darkreader#272] opened 2018-03-09 21:49 UTC
Not working with Firefox Android. The settings screen is blank, no way to turn on.

**Comment by gaul** [comment] 2018-03-11 02:44
Duplicate of #245.

**Closed** 2018-03-11 18:45 UTC
Labels: duplicate

**Comment by alexanderby** [comment] 2018-03-27 17:27
Should work now. Static Theme is used by default, FIlters are slow on smartphones and decrease battery life.
